### ISSUE TITLE
Theme isn't fully done yet?

### ISSUE THREAD

**Issue by lumii500pg** [catppuccin/steam#21]
# My Theme looks like this:
![preview](https://user-images.githubusercontent.com/54220441/234852193-36985b44-c4ba-4caa-b767-03ff39b6af14.png)

### I dunno if this is intended behaviour but for me it seems like that the catppuccin theme isn't fully done yet it looks very metro-like (the theme catppuccin-steam is basing on) so I'll list my steps (I'm on Win11 Pro 22H2 btw.):
- downloaded and extracted [original metro](https://github.com/minischetti/metro-for-steam/releases/tag/v4.4)
- downloaded and extracted [up-metro](https://github.com/redsigma/UPMetroSkin/releases/tag/9.1.47) with the main-files from the unofffical 4.x patches
- downloaded and replaced the stuff with the [catppuccin theme files](https://github.com/catppuccin/steam/tree/main/themes/macchiato)
- added [steam-library](https://github.com/AikoMidori/steam-library) files under the steamui-folder
- ran [SFP](https://github.com/PhantomGamers/SFP) (formerly SteamFriendsPatcher)

**Comment by Oman395** [comment]
yeah, it's pretty broken ATM-- we were using webkit.css for most of the library theming, which completely broke when steam did a major UI update. Currently working on a patch, but yeah, it's extremely WIP.
